# Generated by Django 6.0.4 on 2026-04-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_parents_name_alter_parents_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parents',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
