# Generated by Django 6.0.4 on 2026-04-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0002_alter_children_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
    ]
