# Generated by Django 6.0.4 on 2026-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_children_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
